from langchain_core.tools import tool
from langgraph.types import RunnableConfig
from langchain_core.messages import HumanMessage, AIMessage

from src.agents.copywriter import copywriter_agent
from src.models.supervisor_schema import SupervisorState

@tool
async def call_copywriter(state: SupervisorState, config: RunnableConfig):
    """Call the copywriter agent.
    
    The agent is invoked only with the task description generated by the supervisor, and any research reports that have been generated by the researcher.
    """
    copywriter_response = await copywriter_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            "research_reports": state.research_reports,
            },
        config=config,
        )
    
    ai_message = AIMessage(name="copywriter", content=copywriter_response["messages"][-1].content)

    return {"messages": [ai_message]}