from langchain_core.tools import tool
from langgraph.types import RunnableConfig
from langchain_core.messages import HumanMessage, AIMessage

from src.agents.researcher import researcher_agent
from src.models.supervisor_schema import SupervisorState

@tool
async def call_researcher(state: SupervisorState, config: RunnableConfig):
    """Call the researcher agent.
    
    The agent is invoked only with the task description generated by the supervisor, so the context window is not cluttered with the full conversation history of the supervisor.
    """
    research_response = await researcher_agent.ainvoke(
        input={
            "messages": [HumanMessage(content=state.task_description)],
            },
        config=config,
    )

    ai_message = AIMessage(name="researcher", content=research_response["messages"][-1].content)

    return {
        "research_reports": research_response["research_reports"],
        "messages": [ai_message],
        }