import operator
from pydantic import BaseModel
from typing import Annotated
from langgraph.graph import add_messages

class CopyWriterState(BaseModel):
    """The state of the copywriter agent. 
    
    The research_reports attribute is shared with the supervisor state. This allows the supervisor to access the research reports generated by the researcher and share them with the copywriter.
    """
    messages: Annotated[list, add_messages] = []
    research_reports: Annotated[list, operator.add] = []